### ISSUE TITLE
All the links of the readme are not working for me; are you updating it just now?

### ISSUE THREAD

**Issue by lirilC** [DrA1ex/physics-js#2]

**Comment by DrA1ex** [comment]
@lirilC,
There are no pending updated right now, also I checked links and they works for me.

Seems like some local problem in your network/browser.
Can you attach browser [console](https://developer.chrome.com/docs/devtools/console/log/#browser) and [network](https://developer.chrome.com/docs/devtools/network/#load) logs?

**Comment by lirilC** [comment]
They're working now, thanks.
